HotelMedium.Web/Models/Clients.cs
using System;
using System.Collections.Generic;

namespace HotelMedium.Web.Models
{
    public partial class Clients
    {
        public Clients()
        {
            Bills = new HashSet<Bills>();
            Reservations = new HashSet<Reservations>();
            ToursClients = new HashSet<ToursClients>();
        }

        public int ClientId { get; set; }
        public int CityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string CreditCardNumber { get; set; }
        public int CreditCardCsc { get; set; }
        public DateTime DateCardExpiration { get; set; }
        public bool IsDeleted { get; set; }
        public string Sex { get; set; }

        public Cities City { get; set; }
        public ICollection<Bills> Bills { get; set; }
        public ICollection<Reservations> Reservations { get; set; }
        public ICollection<ToursClients> ToursClients { get; set; }
    }
}

HotelMedium.Web/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HotelMedium.Web.Models.ClientViewModels;
using HotelMedium.Web.Models;

namespace HotelMedium.Web.Controllers
{
    public class ClientController : Controller
    {

        private HotelContext _hotelContext;

        public ClientController(HotelContext context)
        {
            _hotelContext = context;
        }

        [HttpGet]
        public IActionResult Add()
        {
            ClientAddVM model = new ClientAddVM();
            model.countries = _hotelContext.Countries.ToList();
            model.cities = _hotelContext.Cities.Where(c => c.CountryId == model.countries.FirstOrDefault(x => x.Name == "BiH").CountryId).ToList();           

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(ClientAddVM model)
        {
            return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public IActionResult GetData(string id)
        {
            int inta = int.Parse(id);
            ClientAddVM c = new ClientAddVM();
            c.cities = _hotelContext.Cities.Where(cr => cr.CountryId == inta).ToList();
            return PartialView("SelectItemView", c);

        }


    }
}

HotelMedium.Web/Views/Client/Add.cshtml
@model HotelMedium.Web.Models.ClientViewModels.ClientAddVM
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>


@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" asp-action="Add" asp-controller="Client">

    <label asp-for="FirstName"></label>
    <input asp-for="FirstName" />
    <br />

    <label asp-for="LastName"></label>
    <input asp-for="LastName" />
    <br />
    <label asp-for="Phone"></label>
    <input asp-for="Phone" />
    <br />
    <label asp-for="Email"></label>
    <input asp-for="Email" />
    <br />
    <label asp-for="Address"></label>
    <input asp-for="Address" />
    <br />
    <label asp-for="CreditCardNumber"></label>
    <input asp-for="CreditCardNumber" />
    <br />
    <label asp-for="CreditCardCsc"></label>
    <input asp-for="CreditCardCsc" />
    <br />
    <label asp-for="DateCardExpiration"></label>
    <input asp-for="DateCardExpiration" />
    <br />
    <label asp-for="Sex"></label>
    <input asp-for="Sex" />
    <br />

    <select id="proba" asp-for="country" asp-items="@(new SelectList(Model.countries,"CountryId","Name"))" onchange="DoSomething();"></select>

    <div id="div1">
        @Html.Partial("SelectItemView", Model)
    </div>
    <input type="submit" value="klik"/>



</form>


<script>

    function DoSomething() {
        var a = $("#proba option:selected").val();

        $.ajax({
            url: '@Url.Action("GetData", "Client")',
            type: 'POST',
            data: {'id':a},
            success: function (result) {
               //success
                $("#div1").html(result);
            },
            error: function (error) {
               //error
                alert("Error");
            }
         });

    }
</script>